src/objects/JLCL_Program_Data_Import__c.object
<CustomObject>
    <description>Object to be used for importing Program Interest Data.</description>
    <fields>
        <fullName>Contact_Email__c</fullName>
        <label>Contact Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Download_Date__c</fullName>
        <label>Download Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Import_Description__c</fullName>
        <label>Import Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Import_Status__c</fullName>
        <label>Import Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program_Name__c</fullName>
        <label>Program Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>JLCL Program Data Import</label>
    <nameField>
        <displayFormat>PDI-{0000}</displayFormat>
        <label>JLCL Program Data Import ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JLCL Program Data Import</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestScheduledJLCLProgramImportBatch.cls
@isTest
private class TestScheduledJLCLProgramImportBatch {
	public static String CRON_EXP = '0 0 0 15 3 ? 2022';

    static testmethod void testScheduledJob() {
        List<JLCL_Program_Data_Import__c> recList = 
            new List<JLCL_Program_Data_Import__c>();
        JLCL_Program_Data_Import__c rec = 
            new JLCL_Program_Data_Import__c(Import_Status__c = 'Error',Contact_Email__c ='test@test.com',Download_Date__c = Date.today(),Program_Name__c = 'Test');
        	insert rec;
        
   
    test.startTest();
     String jobId = System.schedule('ScheduledApexTest',
            CRON_EXP, 
     new ScheduledJLCLProgramImportBatch());
        System.assertEquals(rec.Import_Status__c, 'Error');
     test.stopTest();
     
     JLCL_Program_Data_Import__c newRec = [Select Id, Import_Status__c, Import_Description__c
                                           FROM JLCL_Program_Data_Import__c where Id = :rec.Id];
     System.assertEquals(newRec.Import_Status__c, 'Error');
     System.assertEquals(newRec.Import_Description__c, 'Error: Email not found');
        
        
                                    
 }
}