src/objects/JLCL_Program_Data_Import__c.object
<CustomObject>
    <description>Object to be used for importing Program Interest Data.</description>
    <fields>
        <fullName>Import_Description__c</fullName>
        <label>Import Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Import_Status__c</fullName>
        <label>Import Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>JLCL Program Data Import</label>
    <nameField>
        <displayFormat>PDI-{0000}</displayFormat>
        <label>JLCL Program Data Import ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JLCL Program Data Import</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ScheduledJLCLProgramImportBatch.cls
global class ScheduledJLCLProgramImportBatch implements Schedulable {
	
    global void execute(SchedulableContext ctx) {
    	
        List<JLCL_Program_Data_Import__c> impRecs = 
             [SELECT Id, Import_Status__c, Import_Description__c
              FROM JLCL_Program_Data_Import__c
              WHERE Import_Status__c = 'Error'];
        for (JLCL_Program_Data_Import__c rec:impRecs) {
            rec.Import_Status__c = 'Not Started';
            rec.Import_Description__c = '';
        }
        update impRecs;
        ProgramInterestBatchDataLoad job = new ProgramInterestBatchDataLoad();
        
    }
}